<p><b>PROFIL BANK BTPN</b></p><hr>

<p>Bank Tabungan Pensiunan Nasional disingkat Bank BTPN terlahir dari pemikiran 7 (tujuh) orang dalam suatu perkumpulan pegawai pensiunan militer pada tahun 1958 di Bandung. Ketujuh serangkai tersebut kemudian mendirikan Perkumpulan Bank Pegawai Pensiunan Militer (selanjutnya disebut &rdquo;BAPEMIL&rdquo;) dengan status usaha sebagai perkumpulan yang menerima simpanan dan memberikan pinjaman kepada para anggotanya. BAPEMIL memiliki tujuan yang mulia yakni membantu meringankan beban ekonomi para pensiunan, baik Angkatan Bersenjata Republik Indonesia maupun sipil, yang ketika itu pada umumnya sangat kesulitan bahkan banyak yang terjerat rentenir.<br />
  Berkat kepercayaan yang tinggi dari masyarakat maupun mitra usaha, pada tahun 1986 para anggota perkumpulan BAPEMIL membentuk PT Bank Tabungan Pensiunan Nasional dengan izin usaha sebagai Bank Tabungan dalam rangka memenuhi ketentuan Undang-undang Nomor 14 Tahun 1967 tentang Pokok-Pokok Perbankan untuk melanjutkan kegiatan usaha BAPEMIL.<br />
  Berlakunya Undang-undang Nomor 7 Tahun 1992 tentang Perbankan (sebagaimana selanjutnya diubah dengan Undang-undang Nomor 10 Tahun 1998) yang antara lain menetapkan bahwa status bank hanya ada dua yaitu: Bank Umum dan Bank Perkreditan Rakyat, maka pada tahun 1993 status Bank BTPN diubah dari Bank Tabungan menjadi Bank Umum melalui Surat Keputusan Menteri Keuangan Republik Indonesia No. 055/KM.17/1993 tanggal 22 Maret 1993. Perubahan status Bank BTPN tersebut telah mendapat persetujuan dari Bank Indonesia sebagaimana ditetapkan dalam surat Bank Indonesia No. 26/5/UPBD/PBD2/Bd tanggal 22 April 1993 yang menyatakan status Perseroan sebagai Bank Umum.<br />
  Sebagai Bank Swasta Nasional yang semula memiliki status sebagai Bank Tabungan kemudian berganti menjadi Bank Umum pada tanggal 22 Maret 1993, Bank BTPN memiliki aktivitas pelayanan operasional kepada Nasabah, baik simpanan maupun pinjaman. Namun aktivitas utama Bank BTPN adalah tetap mengkhususkan kepada pelayanan bagi para pensiunan dan pegawai aktif, karena target market Bank BTPN adalah para pensiunan.<br />
  Dalam rangka memperluas kegiatan usahanya, Bank BTPN bekerja sama dengan PT Taspen, sehingga Bank BTPN tidak saja dapat memberikan pinjaman dan pemotongan cicilan pinjaman, tetapi juga dapat melaksanakan &ldquo;Tri Program Taspen&rdquo;, yaitu Pembayaran Tabungan hari Tua, Pembayaran Jamsostek dan Pembayaran Uang Pensiun.<br />
  Terhitung tanggal 12 Maret 2008 bank BTPN telah listing di Bursa efek Jakarta (BEJ) (sekarang Bursa Efek Indonesia) dan resmi menyandang gelar tbk (terbuka). Dan pada tanggal 14 Maret 2008, Texas Pacific Group (TPG)resmi mengakuisisi saham bank BTPN sebesar 71, 61%.<br />
</p>
<p>Misi bank BTPN<br />
&ldquo; BERSAMA KITA CIPTAKAN KESEMPATAN  TUMBUH DAN HIDUP YANG LEBIH BERARTI &ldquo;</p>
<p>Visi bank BTPN<br />
  &ldquo; MENJADI BANK MASS MARKET TERBAIK,  MENGUBAH HIDUP BERJUTA RAKYAT INDONESIA &ldquo;</p>
<p>&nbsp; </p>
